// Package database — token.go.
//
// Confirmation-token verification for destructive database operations
// (drop_db, drop_user, exec_query in destructive mode, export_dump,
// restore_dump). The control plane mints a short-lived token that pins the
// operation type, the agent_id, the target instance, and the specific
// resource being touched; the agent rejects the operation if the token is
// missing, expired, malformed, intended for a different agent, or does not
// match what the agent is being asked to do.
//
// Per-agent secret design (replaces fleet-wide DATABASE_OP_TOKEN_SECRET):
//
//   - Each agent has its own random 32-byte HMAC key, generated by the
//     control plane and delivered over mTLS in the cert-registration response
//     and on every heartbeat (config_updates["op_token_secret"]).
//   - The agent caches the secret in memory only — never on disk.
//   - The token payload includes agent_id; the agent rejects any token whose
//     agent_id does not match its own. This prevents cross-agent replay if a
//     token leaks from one agent to a network position where another agent
//     might receive it.
//   - If no secret has been received yet (fresh agent before first heartbeat),
//     destructive ops fail closed with a clear error.
//
// Wire format (shared with cloudnan-core):
//
//	token = base64url(payload_json) + "." + base64url(hmac_sha256(secret, payload_json))
package database

import (
	"crypto/hmac"
	"crypto/sha256"
	"crypto/subtle"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"strings"
	"sync"
	"time"
)

const opTokenMinSecretLen = 32

// opToken is the JSON payload signed by the control plane. Field names are
// fixed by the wire contract; do not rename without updating the core.
//
// AgentID is new vs. the legacy shared-secret payload — see file-level docs
// for the cross-agent replay defense it provides.
type opToken struct {
	Op         string `json:"op"`
	AgentID    string `json:"agent_id"`
	InstanceID string `json:"instance_id"`
	Target     string `json:"target"`
	ExpiresAt  int64  `json:"expires_at"`
}

// secretStore holds the per-agent HMAC key and the local agent_id used to
// validate the token's agent_id binding. Both are populated by the
// connection layer when the control plane delivers them — see SetOpTokenSecret
// and SetAgentID.
type secretStore struct {
	mu       sync.RWMutex
	secret   []byte
	agentID  string
}

var localStore secretStore

// SetOpTokenSecret installs a freshly-received per-agent HMAC key. Called
// by the agent's connection code when:
//
//   - the cert-registration HTTP response carries an "op_token_secret" field;
//   - a heartbeat response carries config_updates["op_token_secret"];
//   - cert renewal returns a rotated secret.
//
// Passing a nil/empty/short slice clears the cached secret so destructive
// ops fail closed until a valid value is received again.
func SetOpTokenSecret(secret []byte) {
	localStore.mu.Lock()
	defer localStore.mu.Unlock()
	if len(secret) < opTokenMinSecretLen {
		localStore.secret = nil
		return
	}
	// Defensive copy — the caller may reuse the slice.
	cp := make([]byte, len(secret))
	copy(cp, secret)
	localStore.secret = cp
}

// SetAgentID records the agent's own ID so verifyOpToken can enforce the
// payload's agent_id binding. Called once at startup from the agent's
// config-loading code.
func SetAgentID(id string) {
	localStore.mu.Lock()
	defer localStore.mu.Unlock()
	localStore.agentID = strings.TrimSpace(id)
}

// snapshotState reads both the secret and the local agent_id under one lock
// so a concurrent rotation cannot tear the pair.
func (s *secretStore) snapshotState() ([]byte, string) {
	s.mu.RLock()
	defer s.mu.RUnlock()
	if len(s.secret) == 0 {
		return nil, s.agentID
	}
	cp := make([]byte, len(s.secret))
	copy(cp, s.secret)
	return cp, s.agentID
}

// verifyOpToken validates that token is a well-formed signature over a
// payload whose op/agent_id/instance_id/target match the expected values and
// whose expires_at is still in the future. Any deviation is reported as an
// error; the caller MUST treat any non-nil error as a hard reject.
func verifyOpToken(token, expectedOp, expectedInstance, expectedTarget string) error {
	if token == "" {
		return errors.New("missing confirmation token")
	}

	secret, agentID := localStore.snapshotState()
	if len(secret) < opTokenMinSecretLen {
		return errors.New("agent has not received its per-agent op-token secret yet; destructive ops are disabled")
	}
	if agentID == "" {
		return errors.New("agent_id not set on this agent; destructive ops are disabled")
	}

	parts := strings.Split(token, ".")
	if len(parts) != 2 {
		return errors.New("malformed token: expected <payload>.<signature>")
	}
	payloadBytes, err := base64.RawURLEncoding.DecodeString(parts[0])
	if err != nil {
		return fmt.Errorf("malformed token payload: %w", err)
	}
	sigBytes, err := base64.RawURLEncoding.DecodeString(parts[1])
	if err != nil {
		return fmt.Errorf("malformed token signature: %w", err)
	}

	mac := hmac.New(sha256.New, secret)
	mac.Write(payloadBytes)
	expectedSig := mac.Sum(nil)
	if subtle.ConstantTimeCompare(sigBytes, expectedSig) != 1 {
		return errors.New("token signature mismatch")
	}

	var p opToken
	if err := json.Unmarshal(payloadBytes, &p); err != nil {
		return fmt.Errorf("token payload unmarshal: %w", err)
	}

	if p.AgentID != agentID {
		// Cross-agent replay attempt or misrouted token. Constant-time
		// comparison isn't strictly necessary here because agent_id is not
		// secret, but the message deliberately doesn't echo the value.
		return errors.New("token agent_id does not match this agent")
	}
	if p.Op != expectedOp {
		return fmt.Errorf("token op %q does not match operation %q", p.Op, expectedOp)
	}
	if p.InstanceID != expectedInstance {
		return fmt.Errorf("token instance_id %q does not match request instance %q", p.InstanceID, expectedInstance)
	}
	if p.Target != expectedTarget {
		return fmt.Errorf("token target %q does not match resource %q", p.Target, expectedTarget)
	}
	if p.ExpiresAt <= time.Now().Unix() {
		return fmt.Errorf("token expired at %d", p.ExpiresAt)
	}
	return nil
}
