// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/agent.proto

package agent

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommandType int32

const (
	CommandType_COMMAND_TYPE_UNSPECIFIED CommandType = 0
	CommandType_COMMAND_TYPE_EXEC        CommandType = 1 // Execute shell command
	CommandType_COMMAND_TYPE_INSTALL     CommandType = 2 // apt/yum install
	CommandType_COMMAND_TYPE_SERVICE     CommandType = 3 // systemctl start/stop/restart
	CommandType_COMMAND_TYPE_DOCKER      CommandType = 4 // Docker operations
	CommandType_COMMAND_TYPE_FILE        CommandType = 5 // File operations (read/write/delete)
	CommandType_COMMAND_TYPE_SCRIPT      CommandType = 6 // Execute script content
)

// Enum value maps for CommandType.
var (
	CommandType_name = map[int32]string{
		0: "COMMAND_TYPE_UNSPECIFIED",
		1: "COMMAND_TYPE_EXEC",
		2: "COMMAND_TYPE_INSTALL",
		3: "COMMAND_TYPE_SERVICE",
		4: "COMMAND_TYPE_DOCKER",
		5: "COMMAND_TYPE_FILE",
		6: "COMMAND_TYPE_SCRIPT",
	}
	CommandType_value = map[string]int32{
		"COMMAND_TYPE_UNSPECIFIED": 0,
		"COMMAND_TYPE_EXEC":        1,
		"COMMAND_TYPE_INSTALL":     2,
		"COMMAND_TYPE_SERVICE":     3,
		"COMMAND_TYPE_DOCKER":      4,
		"COMMAND_TYPE_FILE":        5,
		"COMMAND_TYPE_SCRIPT":      6,
	}
)

func (x CommandType) Enum() *CommandType {
	p := new(CommandType)
	*p = x
	return p
}

func (x CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_agent_proto_enumTypes[0].Descriptor()
}

func (CommandType) Type() protoreflect.EnumType {
	return &file_proto_agent_proto_enumTypes[0]
}

func (x CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandType.Descriptor instead.
func (CommandType) EnumDescriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{0}
}

type CommandStatus int32

const (
	CommandStatus_COMMAND_STATUS_UNSPECIFIED CommandStatus = 0
	CommandStatus_COMMAND_STATUS_PENDING     CommandStatus = 1
	CommandStatus_COMMAND_STATUS_RUNNING     CommandStatus = 2
	CommandStatus_COMMAND_STATUS_COMPLETED   CommandStatus = 3
	CommandStatus_COMMAND_STATUS_FAILED      CommandStatus = 4
	CommandStatus_COMMAND_STATUS_TIMEOUT     CommandStatus = 5
	CommandStatus_COMMAND_STATUS_CANCELLED   CommandStatus = 6
)

// Enum value maps for CommandStatus.
var (
	CommandStatus_name = map[int32]string{
		0: "COMMAND_STATUS_UNSPECIFIED",
		1: "COMMAND_STATUS_PENDING",
		2: "COMMAND_STATUS_RUNNING",
		3: "COMMAND_STATUS_COMPLETED",
		4: "COMMAND_STATUS_FAILED",
		5: "COMMAND_STATUS_TIMEOUT",
		6: "COMMAND_STATUS_CANCELLED",
	}
	CommandStatus_value = map[string]int32{
		"COMMAND_STATUS_UNSPECIFIED": 0,
		"COMMAND_STATUS_PENDING":     1,
		"COMMAND_STATUS_RUNNING":     2,
		"COMMAND_STATUS_COMPLETED":   3,
		"COMMAND_STATUS_FAILED":      4,
		"COMMAND_STATUS_TIMEOUT":     5,
		"COMMAND_STATUS_CANCELLED":   6,
	}
)

func (x CommandStatus) Enum() *CommandStatus {
	p := new(CommandStatus)
	*p = x
	return p
}

func (x CommandStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_agent_proto_enumTypes[1].Descriptor()
}

func (CommandStatus) Type() protoreflect.EnumType {
	return &file_proto_agent_proto_enumTypes[1]
}

func (x CommandStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandStatus.Descriptor instead.
func (CommandStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{1}
}

type LogLevel int32

const (
	LogLevel_LOG_LEVEL_UNSPECIFIED LogLevel = 0
	LogLevel_LOG_LEVEL_DEBUG       LogLevel = 1
	LogLevel_LOG_LEVEL_INFO        LogLevel = 2
	LogLevel_LOG_LEVEL_WARN        LogLevel = 3
	LogLevel_LOG_LEVEL_ERROR       LogLevel = 4
)

// Enum value maps for LogLevel.
var (
	LogLevel_name = map[int32]string{
		0: "LOG_LEVEL_UNSPECIFIED",
		1: "LOG_LEVEL_DEBUG",
		2: "LOG_LEVEL_INFO",
		3: "LOG_LEVEL_WARN",
		4: "LOG_LEVEL_ERROR",
	}
	LogLevel_value = map[string]int32{
		"LOG_LEVEL_UNSPECIFIED": 0,
		"LOG_LEVEL_DEBUG":       1,
		"LOG_LEVEL_INFO":        2,
		"LOG_LEVEL_WARN":        3,
		"LOG_LEVEL_ERROR":       4,
	}
)

func (x LogLevel) Enum() *LogLevel {
	p := new(LogLevel)
	*p = x
	return p
}

func (x LogLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_agent_proto_enumTypes[2].Descriptor()
}

func (LogLevel) Type() protoreflect.EnumType {
	return &file_proto_agent_proto_enumTypes[2]
}

func (x LogLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogLevel.Descriptor instead.
func (LogLevel) EnumDescriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{2}
}

type AgentStatus int32

const (
	AgentStatus_AGENT_STATUS_UNSPECIFIED AgentStatus = 0
	AgentStatus_AGENT_STATUS_IDLE        AgentStatus = 1
	AgentStatus_AGENT_STATUS_BUSY        AgentStatus = 2
	AgentStatus_AGENT_STATUS_ERROR       AgentStatus = 3
)

// Enum value maps for AgentStatus.
var (
	AgentStatus_name = map[int32]string{
		0: "AGENT_STATUS_UNSPECIFIED",
		1: "AGENT_STATUS_IDLE",
		2: "AGENT_STATUS_BUSY",
		3: "AGENT_STATUS_ERROR",
	}
	AgentStatus_value = map[string]int32{
		"AGENT_STATUS_UNSPECIFIED": 0,
		"AGENT_STATUS_IDLE":        1,
		"AGENT_STATUS_BUSY":        2,
		"AGENT_STATUS_ERROR":       3,
	}
)

func (x AgentStatus) Enum() *AgentStatus {
	p := new(AgentStatus)
	*p = x
	return p
}

func (x AgentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_agent_proto_enumTypes[3].Descriptor()
}

func (AgentStatus) Type() protoreflect.EnumType {
	return &file_proto_agent_proto_enumTypes[3]
}

func (x AgentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentStatus.Descriptor instead.
func (AgentStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{3}
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`                                                          // Unique agent identifier (generated or assigned)
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`                                                                       // VPS hostname
	IpAddress     string                 `protobuf:"bytes,3,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`                                                    // Public IP
	Os            string                 `protobuf:"bytes,4,opt,name=os,proto3" json:"os,omitempty"`                                                                                   // e.g., "ubuntu", "debian", "centos"
	OsVersion     string                 `protobuf:"bytes,5,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`                                                    // e.g., "22.04"
	Arch          string                 `protobuf:"bytes,6,opt,name=arch,proto3" json:"arch,omitempty"`                                                                               // e.g., "amd64", "arm64"
	AgentVersion  string                 `protobuf:"bytes,7,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`                                           // Agent binary version
	Labels        map[string]string      `protobuf:"bytes,8,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Custom labels for grouping
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_proto_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RegisterRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *RegisterRequest) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *RegisterRequest) GetOsVersion() string {
	if x != nil {
		return x.OsVersion
	}
	return ""
}

func (x *RegisterRequest) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *RegisterRequest) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *RegisterRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type RegisterResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Success           bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message           string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	AssignedId        string                 `protobuf:"bytes,3,opt,name=assigned_id,json=assignedId,proto3" json:"assigned_id,omitempty"`                       // Control Plane may assign a different ID
	HeartbeatInterval int32                  `protobuf:"varint,4,opt,name=heartbeat_interval,json=heartbeatInterval,proto3" json:"heartbeat_interval,omitempty"` // Seconds between heartbeats
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_proto_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterResponse) GetAssignedId() string {
	if x != nil {
		return x.AssignedId
	}
	return ""
}

func (x *RegisterResponse) GetHeartbeatInterval() int32 {
	if x != nil {
		return x.HeartbeatInterval
	}
	return 0
}

type Command struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                                             // Unique command ID
	Type           CommandType            `protobuf:"varint,2,opt,name=type,proto3,enum=agent.CommandType" json:"type,omitempty"`                                                 // Type of command
	Args           []string               `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`                                                                         // Command arguments
	Env            map[string]string      `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Environment variables
	TimeoutSeconds int32                  `protobuf:"varint,5,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`                              // Max execution time (0 = no limit)
	StreamOutput   bool                   `protobuf:"varint,6,opt,name=stream_output,json=streamOutput,proto3" json:"stream_output,omitempty"`                                    // Stream stdout/stderr in real-time
	WorkingDir     string                 `protobuf:"bytes,7,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`                                           // Working directory for command
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_proto_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{2}
}

func (x *Command) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Command) GetType() CommandType {
	if x != nil {
		return x.Type
	}
	return CommandType_COMMAND_TYPE_UNSPECIFIED
}

func (x *Command) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *Command) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *Command) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *Command) GetStreamOutput() bool {
	if x != nil {
		return x.StreamOutput
	}
	return false
}

func (x *Command) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

type CommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Status        CommandStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=agent.CommandStatus" json:"status,omitempty"`
	ExitCode      int32                  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Stdout        string                 `protobuf:"bytes,4,opt,name=stdout,proto3" json:"stdout,omitempty"` // For streaming, partial output
	Stderr        string                 `protobuf:"bytes,5,opt,name=stderr,proto3" json:"stderr,omitempty"`
	StartedAt     int64                  `protobuf:"varint,6,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`       // Unix timestamp
	CompletedAt   int64                  `protobuf:"varint,7,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"` // Unix timestamp (0 if still running)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResponse) Reset() {
	*x = CommandResponse{}
	mi := &file_proto_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResponse) ProtoMessage() {}

func (x *CommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResponse.ProtoReflect.Descriptor instead.
func (*CommandResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{3}
}

func (x *CommandResponse) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandResponse) GetStatus() CommandStatus {
	if x != nil {
		return x.Status
	}
	return CommandStatus_COMMAND_STATUS_UNSPECIFIED
}

func (x *CommandResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *CommandResponse) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *CommandResponse) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *CommandResponse) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *CommandResponse) GetCompletedAt() int64 {
	if x != nil {
		return x.CompletedAt
	}
	return 0
}

type MetricsData struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	AgentId   string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Timestamp int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Unix timestamp
	// CPU
	CpuPercent float64   `protobuf:"fixed64,3,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`          // Overall CPU usage %
	CpuPerCore []float64 `protobuf:"fixed64,4,rep,packed,name=cpu_per_core,json=cpuPerCore,proto3" json:"cpu_per_core,omitempty"` // Per-core usage
	// Memory
	MemoryTotal     uint64  `protobuf:"varint,5,opt,name=memory_total,json=memoryTotal,proto3" json:"memory_total,omitempty"` // Total RAM in bytes
	MemoryUsed      uint64  `protobuf:"varint,6,opt,name=memory_used,json=memoryUsed,proto3" json:"memory_used,omitempty"`    // Used RAM in bytes
	MemoryAvailable uint64  `protobuf:"varint,7,opt,name=memory_available,json=memoryAvailable,proto3" json:"memory_available,omitempty"`
	MemoryPercent   float64 `protobuf:"fixed64,8,opt,name=memory_percent,json=memoryPercent,proto3" json:"memory_percent,omitempty"`
	// Disk
	Disks []*DiskMetrics `protobuf:"bytes,9,rep,name=disks,proto3" json:"disks,omitempty"`
	// Network
	NetworkBytesSent uint64 `protobuf:"varint,10,opt,name=network_bytes_sent,json=networkBytesSent,proto3" json:"network_bytes_sent,omitempty"`
	NetworkBytesRecv uint64 `protobuf:"varint,11,opt,name=network_bytes_recv,json=networkBytesRecv,proto3" json:"network_bytes_recv,omitempty"`
	// Load average (Linux)
	Load_1  float64 `protobuf:"fixed64,12,opt,name=load_1,json=load1,proto3" json:"load_1,omitempty"`
	Load_5  float64 `protobuf:"fixed64,13,opt,name=load_5,json=load5,proto3" json:"load_5,omitempty"`
	Load_15 float64 `protobuf:"fixed64,14,opt,name=load_15,json=load15,proto3" json:"load_15,omitempty"`
	// Uptime
	UptimeSeconds uint64 `protobuf:"varint,15,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsData) Reset() {
	*x = MetricsData{}
	mi := &file_proto_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsData) ProtoMessage() {}

func (x *MetricsData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsData.ProtoReflect.Descriptor instead.
func (*MetricsData) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{4}
}

func (x *MetricsData) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *MetricsData) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *MetricsData) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *MetricsData) GetCpuPerCore() []float64 {
	if x != nil {
		return x.CpuPerCore
	}
	return nil
}

func (x *MetricsData) GetMemoryTotal() uint64 {
	if x != nil {
		return x.MemoryTotal
	}
	return 0
}

func (x *MetricsData) GetMemoryUsed() uint64 {
	if x != nil {
		return x.MemoryUsed
	}
	return 0
}

func (x *MetricsData) GetMemoryAvailable() uint64 {
	if x != nil {
		return x.MemoryAvailable
	}
	return 0
}

func (x *MetricsData) GetMemoryPercent() float64 {
	if x != nil {
		return x.MemoryPercent
	}
	return 0
}

func (x *MetricsData) GetDisks() []*DiskMetrics {
	if x != nil {
		return x.Disks
	}
	return nil
}

func (x *MetricsData) GetNetworkBytesSent() uint64 {
	if x != nil {
		return x.NetworkBytesSent
	}
	return 0
}

func (x *MetricsData) GetNetworkBytesRecv() uint64 {
	if x != nil {
		return x.NetworkBytesRecv
	}
	return 0
}

func (x *MetricsData) GetLoad_1() float64 {
	if x != nil {
		return x.Load_1
	}
	return 0
}

func (x *MetricsData) GetLoad_5() float64 {
	if x != nil {
		return x.Load_5
	}
	return 0
}

func (x *MetricsData) GetLoad_15() float64 {
	if x != nil {
		return x.Load_15
	}
	return 0
}

func (x *MetricsData) GetUptimeSeconds() uint64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

type DiskMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MountPoint    string                 `protobuf:"bytes,1,opt,name=mount_point,json=mountPoint,proto3" json:"mount_point,omitempty"`
	Device        string                 `protobuf:"bytes,2,opt,name=device,proto3" json:"device,omitempty"`
	Total         uint64                 `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	Used          uint64                 `protobuf:"varint,4,opt,name=used,proto3" json:"used,omitempty"`
	Free          uint64                 `protobuf:"varint,5,opt,name=free,proto3" json:"free,omitempty"`
	Percent       float64                `protobuf:"fixed64,6,opt,name=percent,proto3" json:"percent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiskMetrics) Reset() {
	*x = DiskMetrics{}
	mi := &file_proto_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskMetrics) ProtoMessage() {}

func (x *DiskMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskMetrics.ProtoReflect.Descriptor instead.
func (*DiskMetrics) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{5}
}

func (x *DiskMetrics) GetMountPoint() string {
	if x != nil {
		return x.MountPoint
	}
	return ""
}

func (x *DiskMetrics) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *DiskMetrics) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *DiskMetrics) GetUsed() uint64 {
	if x != nil {
		return x.Used
	}
	return 0
}

func (x *DiskMetrics) GetFree() uint64 {
	if x != nil {
		return x.Free
	}
	return 0
}

func (x *DiskMetrics) GetPercent() float64 {
	if x != nil {
		return x.Percent
	}
	return 0
}

type MetricsAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Received      bool                   `protobuf:"varint,1,opt,name=received,proto3" json:"received,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsAck) Reset() {
	*x = MetricsAck{}
	mi := &file_proto_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsAck) ProtoMessage() {}

func (x *MetricsAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsAck.ProtoReflect.Descriptor instead.
func (*MetricsAck) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{6}
}

func (x *MetricsAck) GetReceived() bool {
	if x != nil {
		return x.Received
	}
	return false
}

type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Level         LogLevel               `protobuf:"varint,3,opt,name=level,proto3,enum=agent.LogLevel" json:"level,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"` // "agent", "command:123", "service:nginx"
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_proto_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{7}
}

func (x *LogEntry) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *LogEntry) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *LogEntry) GetLevel() LogLevel {
	if x != nil {
		return x.Level
	}
	return LogLevel_LOG_LEVEL_UNSPECIFIED
}

func (x *LogEntry) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEntry) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type LogAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Received      bool                   `protobuf:"varint,1,opt,name=received,proto3" json:"received,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogAck) Reset() {
	*x = LogAck{}
	mi := &file_proto_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogAck) ProtoMessage() {}

func (x *LogAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogAck.ProtoReflect.Descriptor instead.
func (*LogAck) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{8}
}

func (x *LogAck) GetReceived() bool {
	if x != nil {
		return x.Received
	}
	return false
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Status        AgentStatus            `protobuf:"varint,3,opt,name=status,proto3,enum=agent.AgentStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_proto_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{9}
}

func (x *HeartbeatRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *HeartbeatRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HeartbeatRequest) GetStatus() AgentStatus {
	if x != nil {
		return x.Status
	}
	return AgentStatus_AGENT_STATUS_UNSPECIFIED
}

type HeartbeatResponse struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	ServerTime   int64                  `protobuf:"varint,2,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	// Control plane can send config updates
	ConfigUpdates map[string]string `protobuf:"bytes,3,rep,name=config_updates,json=configUpdates,proto3" json:"config_updates,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_proto_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{10}
}

func (x *HeartbeatResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *HeartbeatResponse) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

func (x *HeartbeatResponse) GetConfigUpdates() map[string]string {
	if x != nil {
		return x.ConfigUpdates
	}
	return nil
}

var File_proto_agent_proto protoreflect.FileDescriptor

const file_proto_agent_proto_rawDesc = "" +
	"\n" +
	"\x11proto/agent.proto\x12\x05agent\"\xc6\x02\n" +
	"\x0fRegisterRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x03 \x01(\tR\tipAddress\x12\x0e\n" +
	"\x02os\x18\x04 \x01(\tR\x02os\x12\x1d\n" +
	"\n" +
	"os_version\x18\x05 \x01(\tR\tosVersion\x12\x12\n" +
	"\x04arch\x18\x06 \x01(\tR\x04arch\x12#\n" +
	"\ragent_version\x18\a \x01(\tR\fagentVersion\x12:\n" +
	"\x06labels\x18\b \x03(\v2\".agent.RegisterRequest.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x96\x01\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vassigned_id\x18\x03 \x01(\tR\n" +
	"assignedId\x12-\n" +
	"\x12heartbeat_interval\x18\x04 \x01(\x05R\x11heartbeatInterval\"\xa7\x02\n" +
	"\aCommand\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12&\n" +
	"\x04type\x18\x02 \x01(\x0e2\x12.agent.CommandTypeR\x04type\x12\x12\n" +
	"\x04args\x18\x03 \x03(\tR\x04args\x12)\n" +
	"\x03env\x18\x04 \x03(\v2\x17.agent.Command.EnvEntryR\x03env\x12'\n" +
	"\x0ftimeout_seconds\x18\x05 \x01(\x05R\x0etimeoutSeconds\x12#\n" +
	"\rstream_output\x18\x06 \x01(\bR\fstreamOutput\x12\x1f\n" +
	"\vworking_dir\x18\a \x01(\tR\n" +
	"workingDir\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xed\x01\n" +
	"\x0fCommandResponse\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12,\n" +
	"\x06status\x18\x02 \x01(\x0e2\x14.agent.CommandStatusR\x06status\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06stdout\x18\x04 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x05 \x01(\tR\x06stderr\x12\x1d\n" +
	"\n" +
	"started_at\x18\x06 \x01(\x03R\tstartedAt\x12!\n" +
	"\fcompleted_at\x18\a \x01(\x03R\vcompletedAt\"\x93\x04\n" +
	"\vMetricsData\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x1f\n" +
	"\vcpu_percent\x18\x03 \x01(\x01R\n" +
	"cpuPercent\x12 \n" +
	"\fcpu_per_core\x18\x04 \x03(\x01R\n" +
	"cpuPerCore\x12!\n" +
	"\fmemory_total\x18\x05 \x01(\x04R\vmemoryTotal\x12\x1f\n" +
	"\vmemory_used\x18\x06 \x01(\x04R\n" +
	"memoryUsed\x12)\n" +
	"\x10memory_available\x18\a \x01(\x04R\x0fmemoryAvailable\x12%\n" +
	"\x0ememory_percent\x18\b \x01(\x01R\rmemoryPercent\x12(\n" +
	"\x05disks\x18\t \x03(\v2\x12.agent.DiskMetricsR\x05disks\x12,\n" +
	"\x12network_bytes_sent\x18\n" +
	" \x01(\x04R\x10networkBytesSent\x12,\n" +
	"\x12network_bytes_recv\x18\v \x01(\x04R\x10networkBytesRecv\x12\x15\n" +
	"\x06load_1\x18\f \x01(\x01R\x05load1\x12\x15\n" +
	"\x06load_5\x18\r \x01(\x01R\x05load5\x12\x17\n" +
	"\aload_15\x18\x0e \x01(\x01R\x06load15\x12%\n" +
	"\x0euptime_seconds\x18\x0f \x01(\x04R\ruptimeSeconds\"\x9e\x01\n" +
	"\vDiskMetrics\x12\x1f\n" +
	"\vmount_point\x18\x01 \x01(\tR\n" +
	"mountPoint\x12\x16\n" +
	"\x06device\x18\x02 \x01(\tR\x06device\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x04R\x05total\x12\x12\n" +
	"\x04used\x18\x04 \x01(\x04R\x04used\x12\x12\n" +
	"\x04free\x18\x05 \x01(\x04R\x04free\x12\x18\n" +
	"\apercent\x18\x06 \x01(\x01R\apercent\"(\n" +
	"\n" +
	"MetricsAck\x12\x1a\n" +
	"\breceived\x18\x01 \x01(\bR\breceived\"\x94\x02\n" +
	"\bLogEntry\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12%\n" +
	"\x05level\x18\x03 \x01(\x0e2\x0f.agent.LogLevelR\x05level\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x129\n" +
	"\bmetadata\x18\x06 \x03(\v2\x1d.agent.LogEntry.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"$\n" +
	"\x06LogAck\x12\x1a\n" +
	"\breceived\x18\x01 \x01(\bR\breceived\"w\n" +
	"\x10HeartbeatRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12*\n" +
	"\x06status\x18\x03 \x01(\x0e2\x12.agent.AgentStatusR\x06status\"\xee\x01\n" +
	"\x11HeartbeatResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\x12\x1f\n" +
	"\vserver_time\x18\x02 \x01(\x03R\n" +
	"serverTime\x12R\n" +
	"\x0econfig_updates\x18\x03 \x03(\v2+.agent.HeartbeatResponse.ConfigUpdatesEntryR\rconfigUpdates\x1a@\n" +
	"\x12ConfigUpdatesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\xbf\x01\n" +
	"\vCommandType\x12\x1c\n" +
	"\x18COMMAND_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11COMMAND_TYPE_EXEC\x10\x01\x12\x18\n" +
	"\x14COMMAND_TYPE_INSTALL\x10\x02\x12\x18\n" +
	"\x14COMMAND_TYPE_SERVICE\x10\x03\x12\x17\n" +
	"\x13COMMAND_TYPE_DOCKER\x10\x04\x12\x15\n" +
	"\x11COMMAND_TYPE_FILE\x10\x05\x12\x17\n" +
	"\x13COMMAND_TYPE_SCRIPT\x10\x06*\xda\x01\n" +
	"\rCommandStatus\x12\x1e\n" +
	"\x1aCOMMAND_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16COMMAND_STATUS_PENDING\x10\x01\x12\x1a\n" +
	"\x16COMMAND_STATUS_RUNNING\x10\x02\x12\x1c\n" +
	"\x18COMMAND_STATUS_COMPLETED\x10\x03\x12\x19\n" +
	"\x15COMMAND_STATUS_FAILED\x10\x04\x12\x1a\n" +
	"\x16COMMAND_STATUS_TIMEOUT\x10\x05\x12\x1c\n" +
	"\x18COMMAND_STATUS_CANCELLED\x10\x06*w\n" +
	"\bLogLevel\x12\x19\n" +
	"\x15LOG_LEVEL_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fLOG_LEVEL_DEBUG\x10\x01\x12\x12\n" +
	"\x0eLOG_LEVEL_INFO\x10\x02\x12\x12\n" +
	"\x0eLOG_LEVEL_WARN\x10\x03\x12\x13\n" +
	"\x0fLOG_LEVEL_ERROR\x10\x04*q\n" +
	"\vAgentStatus\x12\x1c\n" +
	"\x18AGENT_STATUS_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11AGENT_STATUS_IDLE\x10\x01\x12\x15\n" +
	"\x11AGENT_STATUS_BUSY\x10\x02\x12\x16\n" +
	"\x12AGENT_STATUS_ERROR\x10\x032\xb6\x02\n" +
	"\fAgentService\x12;\n" +
	"\bRegister\x12\x16.agent.RegisterRequest\x1a\x17.agent.RegisterResponse\x12;\n" +
	"\rCommandStream\x12\x16.agent.CommandResponse\x1a\x0e.agent.Command(\x010\x01\x12:\n" +
	"\rStreamMetrics\x12\x12.agent.MetricsData\x1a\x11.agent.MetricsAck(\x010\x01\x120\n" +
	"\n" +
	"StreamLogs\x12\x0f.agent.LogEntry\x1a\r.agent.LogAck(\x010\x01\x12>\n" +
	"\tHeartbeat\x12\x17.agent.HeartbeatRequest\x1a\x18.agent.HeartbeatResponseB3Z1github.com/budhilaw/malangpanel-agent/proto/agentb\x06proto3"

var (
	file_proto_agent_proto_rawDescOnce sync.Once
	file_proto_agent_proto_rawDescData []byte
)

func file_proto_agent_proto_rawDescGZIP() []byte {
	file_proto_agent_proto_rawDescOnce.Do(func() {
		file_proto_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_agent_proto_rawDesc), len(file_proto_agent_proto_rawDesc)))
	})
	return file_proto_agent_proto_rawDescData
}

var file_proto_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_proto_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_agent_proto_goTypes = []any{
	(CommandType)(0),          // 0: agent.CommandType
	(CommandStatus)(0),        // 1: agent.CommandStatus
	(LogLevel)(0),             // 2: agent.LogLevel
	(AgentStatus)(0),          // 3: agent.AgentStatus
	(*RegisterRequest)(nil),   // 4: agent.RegisterRequest
	(*RegisterResponse)(nil),  // 5: agent.RegisterResponse
	(*Command)(nil),           // 6: agent.Command
	(*CommandResponse)(nil),   // 7: agent.CommandResponse
	(*MetricsData)(nil),       // 8: agent.MetricsData
	(*DiskMetrics)(nil),       // 9: agent.DiskMetrics
	(*MetricsAck)(nil),        // 10: agent.MetricsAck
	(*LogEntry)(nil),          // 11: agent.LogEntry
	(*LogAck)(nil),            // 12: agent.LogAck
	(*HeartbeatRequest)(nil),  // 13: agent.HeartbeatRequest
	(*HeartbeatResponse)(nil), // 14: agent.HeartbeatResponse
	nil,                       // 15: agent.RegisterRequest.LabelsEntry
	nil,                       // 16: agent.Command.EnvEntry
	nil,                       // 17: agent.LogEntry.MetadataEntry
	nil,                       // 18: agent.HeartbeatResponse.ConfigUpdatesEntry
}
var file_proto_agent_proto_depIdxs = []int32{
	15, // 0: agent.RegisterRequest.labels:type_name -> agent.RegisterRequest.LabelsEntry
	0,  // 1: agent.Command.type:type_name -> agent.CommandType
	16, // 2: agent.Command.env:type_name -> agent.Command.EnvEntry
	1,  // 3: agent.CommandResponse.status:type_name -> agent.CommandStatus
	9,  // 4: agent.MetricsData.disks:type_name -> agent.DiskMetrics
	2,  // 5: agent.LogEntry.level:type_name -> agent.LogLevel
	17, // 6: agent.LogEntry.metadata:type_name -> agent.LogEntry.MetadataEntry
	3,  // 7: agent.HeartbeatRequest.status:type_name -> agent.AgentStatus
	18, // 8: agent.HeartbeatResponse.config_updates:type_name -> agent.HeartbeatResponse.ConfigUpdatesEntry
	4,  // 9: agent.AgentService.Register:input_type -> agent.RegisterRequest
	7,  // 10: agent.AgentService.CommandStream:input_type -> agent.CommandResponse
	8,  // 11: agent.AgentService.StreamMetrics:input_type -> agent.MetricsData
	11, // 12: agent.AgentService.StreamLogs:input_type -> agent.LogEntry
	13, // 13: agent.AgentService.Heartbeat:input_type -> agent.HeartbeatRequest
	5,  // 14: agent.AgentService.Register:output_type -> agent.RegisterResponse
	6,  // 15: agent.AgentService.CommandStream:output_type -> agent.Command
	10, // 16: agent.AgentService.StreamMetrics:output_type -> agent.MetricsAck
	12, // 17: agent.AgentService.StreamLogs:output_type -> agent.LogAck
	14, // 18: agent.AgentService.Heartbeat:output_type -> agent.HeartbeatResponse
	14, // [14:19] is the sub-list for method output_type
	9,  // [9:14] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_proto_agent_proto_init() }
func file_proto_agent_proto_init() {
	if File_proto_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_agent_proto_rawDesc), len(file_proto_agent_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_agent_proto_goTypes,
		DependencyIndexes: file_proto_agent_proto_depIdxs,
		EnumInfos:         file_proto_agent_proto_enumTypes,
		MessageInfos:      file_proto_agent_proto_msgTypes,
	}.Build()
	File_proto_agent_proto = out.File
	file_proto_agent_proto_goTypes = nil
	file_proto_agent_proto_depIdxs = nil
}
